// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLr3B6LSrxitN5cX7pALw2icraVNI-U8c',
    appId: '1:816048333127:web:4f05de6133c2192fedec62',
    messagingSenderId: '816048333127',
    projectId: 'esnya-food-tracker-development',
    authDomain: 'esnya-food-tracker-development.firebaseapp.com',
    storageBucket: 'esnya-food-tracker-development.appspot.com',
    measurementId: 'G-T127FRG97T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtrmgGkVbG897YdstlBpMvLjzb5iqzZhU',
    appId: '1:816048333127:android:eb1c43f12c6a4c29edec62',
    messagingSenderId: '816048333127',
    projectId: 'esnya-food-tracker-development',
    storageBucket: 'esnya-food-tracker-development.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOL88Ok_yrvYb826Gz5Rg0KryT-i6UZLQ',
    appId: '1:816048333127:ios:ba5cc194fc420e8bedec62',
    messagingSenderId: '816048333127',
    projectId: 'esnya-food-tracker-development',
    storageBucket: 'esnya-food-tracker-development.appspot.com',
    androidClientId: '816048333127-c1r2ehi721m4u292nkp7g6rq4864tvhu.apps.googleusercontent.com',
    iosClientId: '816048333127-t19aosaovm7k4bpjlgflhqc1h5dhhles.apps.googleusercontent.com',
    iosBundleId: 'com.thapps.esnya',
  );
}
